name: docker-build-catgpt

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true
    outputs:
      app-version:
        value: ${{ jobs.build.outputs.app-version }}

jobs:
  build:
    name: Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      app-version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cr.yandex/crp3b70hbcrvtbg25qbk/${{ inputs.app-name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: ${{ secrets.UNAME }}
          password: ${{ secrets.PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          context: ./catgpt
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
