name: Docker Build and Deploy catgpt

on:
  push:
    tags:
      - '*'  # Любой тег

jobs:
  build-and-deploy:
    if: ${{ github.path == './catgpt' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Yandex
        run: docker login -u ${{ secrets.YANDEX_USERNAME }} -p ${{ secrets.YANDEX_CLOUD_SERVICE_ACCOUNT_KEY }}  cr.yandex/crp3b70hbcrvtbg25qbk
      - name: Build and push Docker image
        run: |
          docker build -t ikfellk/catgpt:v1 .
          docker tag ikfellk/catgpt:v1 cr.yandex/crp3b70hbcrvtbg25qbk/ikfellkcatgpt
          docker push cr.yandex/crp3b70hbcrvtbg25qbk/ikfellkcatgpt
